### ISSUE TITLE
the function ‘Sheet.setColAutoFit’ seems not work

### ISSUE THREAD

**Issue by StephinChou** [justkawal/excel#265]
![image](https://github.com/justkawal/excel/assets/6660127/0e39a315-274d-4dd4-af6c-c8045dfe11ea)

excel version: 
`excel: ^2.1.0`

my code:
```dart
    var excel = Excel.createExcel();
    Sheet sheet = excel['Sheet1'];
   /// write some data to cells

  /// and we set the width and the autofit property,  the A1 and B1 column
    sheet.setColWidth(0, 30);
    sheet.setColAutoFit(0);
    sheet.setColWidth(1, 30);
    sheet.setColAutoFit(1);

   sheet.save();
```
then i got this excel below: 
![image](https://github.com/justkawal/excel/assets/6660127/4b41f9c1-ae36-4026-9816-2522d3780461)
![image](https://github.com/justkawal/excel/assets/6660127/e9726378-b452-4a72-823a-fcd392c74374)

so the `autofit` seems not works and ,
by the way ,  `setColWidth` function looks like that  it just effects the *last call*.
in my case,  I called the  `setColWidth` function in column A1 and B1,  but just the B1 cell changed width.

**Comment by FauconSpartiate** [comment]
Should be fixed in #245, will be released in 3.0.0 soon.
In the meantime, you can try to declare the package with the github link in your `pubspec.yaml` to test with the latest commits and see if it's fixed.

**Comment by FauconSpartiate** [comment]
`3.0.0` has been released, can you check is the issue is fixed?

**Comment by dm-ra-01** [comment]
Hello, I have the same issue where executing setColumnWidth(i, 5) only updates the last column. This remains on version 3.0.0. 

Print(sheet.getColumnWidths) returns the correct values, though the issue remains:
`` {0: 5, 1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5}

Could  save_file.dart be the culprit? 

      if (index != 0 && columnWidths[index - 1] != width) {
        _addNewColumn(columns, min, index - 1, columnWidths[index - 1]);
        min = index;
      }

      if (index == (columnCount - 1)) {
        _addNewColumn(columns, index, index, width);
      }

Code reference: https://github.com/justkawal/excel/blob/039c66f66408c3480857851db998515d4afee0bd/lib/src/save/save_file.dart#L443C1-L451C1

Thanks in advance

**Comment by FauconSpartiate** [comment]
@justkawal What does [this code](https://github.com/justkawal/excel/blob/039c66f66408c3480857851db998515d4afee0bd/lib/src/save/save_file.dart#L443C1-L451C1) do exactly and what is its purpose?

Simply replacing by:
```dart
_addNewColumn(columns, index, index, width);
```
fixes the bug and does the job, but I don't want to break anything else, are there any edge cases I didn't consider?
